Repository QuasarApp/Hanoi-Towers, pull requests merged in 2021-06, with the labels that each got.

#100 Localization (zh): add human translation
  Docs/Zh/ChangeLog.md
  Docs/Zh/Description.md
  HanoiTowers/client/languages/zh.ts
Labels: GUI, bug, documentation

#99 Add new languages and translation
  Docs/De/ChangeLog.md
  Docs/De/Description.md
  Docs/Es/ChangeLog.md
  Docs/Es/Description.md
  Docs/Fr/ChangeLog.md
  Docs/Fr/Description.md
  Docs/Pl/ChangeLog.md
  Docs/Pl/Description.md
  Docs/Zh/ChangeLog.md
  Docs/Zh/Description.md
  HanoiTowers/client/CMakeLists.txt
  HanoiTowers/client/languages/de.ts
  HanoiTowers/client/languages/es.ts
  HanoiTowers/client/languages/fr.ts
  HanoiTowers/client/languages/pl.ts
  HanoiTowers/client/languages/zh.ts
  HanoiTowers/client/qml.qrc
Labels: enhancement

#106 Update changelogs and translations
  Docs/De/ChangeLog.md
  Docs/En/ChangeLog.md
  Docs/Es/ChangeLog.md
  Docs/Fr/ChangeLog.md
  Docs/Ja/ChangeLog.md
  Docs/Pl/ChangeLog.md
  Docs/Ru/ChangeLog.md
  Docs/Tr/ChangeLog.md
  Docs/Ua/ChangeLog.md
  Docs/Zh/ChangeLog.md
  HanoiTowers/client/languages/de.ts
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/es.ts
  HanoiTowers/client/languages/fr.ts
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/pl.ts
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/uk.ts
  HanoiTowers/client/languages/zh.ts
Labels: documentation

#107 Update changelogs
  Docs/De/ChangeLog.md
  Docs/En/ChangeLog.md
  Docs/Es/ChangeLog.md
  Docs/Fr/ChangeLog.md
  Docs/Ja/ChangeLog.md
  Docs/Pl/ChangeLog.md
  Docs/Ru/ChangeLog.md
  Docs/Tr/ChangeLog.md
  Docs/Ua/ChangeLog.md
  Docs/Zh/ChangeLog.md
Labels: documentation

#109 Update translation
  HanoiTowers/client/languages/de.ts
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/es.ts
  HanoiTowers/client/languages/fr.ts
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/pl.ts
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/uk.ts
  HanoiTowers/client/languages/zh.ts
Labels: GUI
