Repository QuasarApp/Hanoi-Towers, pull requests merged in 2021-05, with the labels that each got.

#59 Translation update
  HanoiTowers/client/languages/en.qm
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/ja.qm
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/ru.qm
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.qm
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/ua.qm
  HanoiTowers/client/languages/ua.ts
Labels: GUI

#60 Update translation
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/ua.ts
Labels: GUI

#62 Fix uk translation
  HanoiTowers/client/CMakeLists.txt
  HanoiTowers/client/languages/uk.ts
  HanoiTowers/client/qml.qrc
Labels: bug

#66 Fix translation
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/uk.ts
Labels: GUI

#68 Task 63
  CMakeLists.txt
  HanoiTowers/Protockol/src/gamestate.cpp
  HanoiTowers/client/Game.qml
  HanoiTowers/client/Tower.qml
  HanoiTowers/client/hanoitowers.cpp
  HanoiTowers/client/hanoitowers.h
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/uk.ts
  HanoiTowers/client/main.qml
  README.md
  snap/snapcraft.yaml
Labels: bug

#72 Fix load old settings
  HanoiTowers/client/hanoitowers.cpp
  HanoiTowers/client/hanoitowers.h
Labels: bug

#75 Update changelog
  Docs/En/ChangeLog.md
  Docs/Ja/ChangeLog.md
  Docs/Ru/ChangeLog.md
  Docs/Tr/ChangeLog.md
  Docs/Ua/ChangeLog.md
Labels: documentation

#85 Translation update
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/uk.ts
Labels: GUI

#87 Changelogs updates
  Docs/En/ChangeLog.md
  Docs/Ja/ChangeLog.md
  Docs/Ru/ChangeLog.md
  Docs/Tr/ChangeLog.md
  Docs/Ua/ChangeLog.md
Labels: documentation

#84 Dev
  Docs/En/ChangeLog.md
  Docs/Ja/ChangeLog.md
  Docs/Ru/ChangeLog.md
  Docs/Tr/ChangeLog.md
  Docs/Ua/ChangeLog.md
  HanoiTowers/client/Game.qml
  HanoiTowers/client/admod/AdMobInterstitialAndroid.qml
  HanoiTowers/client/android/AndroidManifest.xml
  HanoiTowers/client/hanoitowers.cpp
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/uk.ts
  HanoiTowers/client/main.qml
  HanoiTowers/client/menu/MainMenu.qml
  HanoiTowers/client/plate.qml
Labels: GUI, bug

#91 Add new logo
  HanoiTowers/client/res/HanoiTowers_premium_logo.png
Labels: GUI

#94 Translation update
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/uk.ts
Labels: GUI
