Repository QuasarApp/Hanoi-Towers, pull requests merged in 2021-02, with the labels that each got.

#39 Translations fix
  HanoiTowers/client/languages/en.qm
  HanoiTowers/client/languages/en.ts
  HanoiTowers/client/languages/ja.qm
  HanoiTowers/client/languages/ja.ts
  HanoiTowers/client/languages/ru.qm
  HanoiTowers/client/languages/ru.ts
  HanoiTowers/client/languages/tr.qm
  HanoiTowers/client/languages/tr.ts
  HanoiTowers/client/languages/ua.qm
  HanoiTowers/client/languages/ua.ts
Labels: Translations

#42 Add change log
  Docs/En/ChangeLog.md
  Docs/Ja/ChangeLog.md
  Docs/Ru/ChangeLog.md
  Docs/Tr/ChangeLog.md
  Docs/Ua/ChangeLog.md
Labels: doc

#45 Add credits in readme
  HanoiTowers/res/Credits.jpg
  README.md
Labels: doc

#47 Save game
  HanoiTowers/res/Sounds/TowerBlockSound.wav
Labels: enhancement
